"use client";
import Footer from '@/components/layout/Footer';
import './globals.css';
import Nav from '@/components/layout/Nav';
import { usePathname } from 'next/navigation';
import Overlay from '@/components/alerts/Overlay';
import { useState } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const excludedPaths = ['/contact', '/register'];

  const [popUp, setPopUp] = useState(false)
  return (
    <html lang="en">
      <body className={`bg-darkBlue font-montserrat relative ${popUp ? 'overflow-hidden' : ''}`}>
          {
            popUp &&
            <div className='absolute left-0 top-0'>
              <Overlay setPopUp={setPopUp}/>
            </div>
          }
        <div className='max-w-[1600px] m-[auto] overflow-hidden'>
          <Nav />
          <div className='px-[60px]'>
            <div>
              {children}
            </div>
          </div>
          {
            excludedPaths.includes(pathname) ? <></> : <Footer />
          }
        </div>
      </body>
    </html>
  )
}
